-- +goose Up
-- +goose StatementBegin
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS allowed_models TEXT NOT NULL DEFAULT '';
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS concurrency_limit INT NOT NULL DEFAULT 0;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS qps_limit INT NOT NULL DEFAULT 0;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS tps_limit INT NOT NULL DEFAULT 0;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS rpm_limit INT NOT NULL DEFAULT 0;
ALTER TABLE tokens ADD COLUMN IF NOT EXISTS tpm_limit INT NOT NULL DEFAULT 0;

ALTER TABLE upstreams ADD COLUMN IF NOT EXISTS tags TEXT NOT NULL DEFAULT '';
ALTER TABLE upstreams ADD COLUMN IF NOT EXISTS auto_disable BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE upstreams ADD COLUMN IF NOT EXISTS failure_count INT NOT NULL DEFAULT 0;
ALTER TABLE upstreams ADD COLUMN IF NOT EXISTS failure_threshold INT NOT NULL DEFAULT 3;
ALTER TABLE upstreams ADD COLUMN IF NOT EXISTS last_error TEXT NOT NULL DEFAULT '';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
ALTER TABLE upstreams DROP COLUMN IF EXISTS last_error;
ALTER TABLE upstreams DROP COLUMN IF EXISTS failure_threshold;
ALTER TABLE upstreams DROP COLUMN IF EXISTS failure_count;
ALTER TABLE upstreams DROP COLUMN IF EXISTS auto_disable;
ALTER TABLE upstreams DROP COLUMN IF EXISTS tags;

ALTER TABLE tokens DROP COLUMN IF EXISTS tpm_limit;
ALTER TABLE tokens DROP COLUMN IF EXISTS rpm_limit;
ALTER TABLE tokens DROP COLUMN IF EXISTS tps_limit;
ALTER TABLE tokens DROP COLUMN IF EXISTS qps_limit;
ALTER TABLE tokens DROP COLUMN IF EXISTS concurrency_limit;
ALTER TABLE tokens DROP COLUMN IF EXISTS allowed_models;
-- +goose StatementEnd
